config/routes.rb
Rails.application.routes.draw do
  

  root 'home#index'

  resources :tests
  resources :users
  resources :courses
  resources :teachers

  resources :teachers do
    resources :teacher_courses
  end

end

app/models/course.rb
class Course < ActiveRecord::Base
	has_many :teacher_course


	def self.search(search)
	  where("name LIKE ?", "%#{search}%")
	end
end

app/models/course_type.rb
class CourseType < ActiveRecord::Base
	has_many :teacher_course
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
	has_many :teacher_course
end

app/models/teacher_course.rb
class TeacherCourse < ActiveRecord::Base
  belongs_to :teacher
  belongs_to :course
  belongs_to :course_type
end

app/models/test.rb
class Test < ActiveRecord::Base
  belongs_to :teacher
  belongs_to :course
  belongs_to :user

  has_attached_file :test
  validates_attachment_content_type :test, :content_type => ['image/jpeg', 'image/png', 'application/pdf']
end

app/models/user.rb
class User < ActiveRecord::Base
	has_attached_file :avatar, styles: {large: "800x600>", medium: "300x300>", thumb: "150x150>"}
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	
	def index
		@courses = Course.all
	end

	def show
		@course = Course.find(params[:id])
	end

	def new
		@course = Course.new
	end

	def create  
		@course = Course.new(course_params)

		if @course.save
			redirect_to @course
		else
			render 'new'
		end
	end

	def destroy
		@course = course.find(params[:id])
		@course.destroy

		redirect_to courses_path
	end

	def edit
		@course = Course.find(params[:id])
	end

	def update
		@course = Course.find(params[:id])

		if @course.update(course_params)
			redirect_to courses_path
		else
			render 'edit'
		end
	end

	# def index
	#   @courses = Course.all
	#   if params[:search]
	#     @posts = Course.search(params[:search]).order("created_at DESC")
	#   else
	#     @posts = Course.all.order('created_at DESC')
	#   end
	# end

	private
	
	def course_params	
		@course = params.require(:course).permit(:name, :nick, :email)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/teacher_courses_controller.rb
class TeacherCoursesController < ApplicationController
  def create
    @teacher = Teacher.find(params[:teacher_id])
    @teacher_course = @teacher.teacher_course.create(teacher_course_params)
    redirect_to teachers_path(@teacher)
  end
 
  private
    def teacher_course_params
      params.require(:teacher_course).permit(:course_id, :course_type_id, :year)
    end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
	
	def index
		@teachers = Teacher.all
	end

	def show
		@teacher = Teacher.find(params[:id])
	end

	def new
		@teacher = Teacher.new
	end

	def create  
		@teacher = Teacher.new(teacher_params)

		if @teacher.save
			redirect_to @teacher
		else
			render 'new'
		end
	end

	def destroy
		@teacher = teacher.find(params[:id])
		@teacher.destroy

		redirect_to teachers_path
	end

	def edit
		@teacher = Teacher.find(params[:id])
	end

	def update
		@teacher = Teacher.find(params[:id])

		if @teacher.update(teacher_params)
			redirect_to teachers_path
		else
			render 'edit'
		end
	end

	private
	
	def teacher_params	
		@teacher = params.require(:teacher).permit(:name, :nick, :email)
	end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
	
	def index
		@tests = Test.all
	end

	def show
		@test = Test.find(params[:id])
	end

	def new
		@test = Test.new
	end

	def create  
		@test = Test.new(test_params)

		if @test.save
			redirect_to @test
		else
			render 'new'
		end
	end

	def destroy
		@test = test.find(params[:id])
		@test.destroy

		redirect_to tests_path
	end

	def edit
		@test = Test.find(params[:id])
	end

	def update
		@test = Test.find(params[:id])

		if @test.update(test_params)
			redirect_to tests_path
		else
			render 'edit'
		end
	end

	private
	
	def test_params	
		@user = params.require(:test).permit(:year, :teacher_id, :course_id, :user_id, :number, :test, :content)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def create  
		@user = User.new(user_params)

		if @user.save
			redirect_to @user
		else
			render 'new'
		end
	end

	def destroy
		@user = user.find(params[:id])
		@user.destroy

		redirect_to users_path
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])

		if @user.update(user_params)
			redirect_to users_path
		else
			render 'edit'
		end
	end

	private
	
	def user_params	
		@user = params.require(:user).permit(:name, :nick, :email, :avatar)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/teacher_courses_helper.rb
module TeacherCoursesHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/courses/edit.html.erb
<h1>Editar Disciplina</h1>
<br />
<%= form_for @course, url: {action: :update}  do |f| %>
	<% if @course.errors.any? %>
		<h2> Tem erro! </h2>
		<ul>
		<% @course.errors.full_messages.each do |message| %>
			<li> <%= message %> </li>
		<% end %>
		</ul>
	<% end %>

	<p>
		<%= f.label :name %> <br />
		<%= f.text_field :name %>
	</p>
	
	<p>
		<%= f.submit "Salvar Disciplina" %>
	</p>
<% end %>

<%= link_to 'Voltar', courses_path %>

app/views/courses/index.html.erb
<div class="page-header">
	<h1><span class="text-light-gray">Provas / </span>Listar</h1>
</div>
<div class="row">
	<div class="col-sm-12">
		<div class="panel">
			<div class="panel-heading">
				<span class="panel-title">Todas as Discplina</span>
			</div>
			<div class="panel-body">
				<table class="table">
					<thead>
						<tr>
							<th>Disciplina</th>
							<th>Professor</th>
							<th>Ano</th>
							<th>Número da prova</th>
							<th>Arquivo</th>
						</tr>
					</thead>
					<tbody>
						<% @tests.each do |t| %>
							<tr>
								<td><%= t.course.name if t.course %></td>
								<td><%= t.teacher.name  if t.teacher %></td>
								<td><%= t.year %></td>
								<td><%= t.number %></td>
								<td><%= link_to "Baixar", root_path %></td>
							</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

app/views/courses/new.html.erb
<h1>Nova disciplina</h1>
<br />

<%= form_for @course do |f| %>
	<% if @course.errors.any? %>
		<h2> Tem erro! </h2>
		<ul>
		<% @course.errors.full_messages.each do |message| %>
			<li> <%= message %> </li>
		<% end %>
		</ul>
	<% end %>

	<p>
		<%= f.label :name %> <br />
		<%= f.text_field :name %>
	</p>
	<p>
		<%= f.submit "Novo Disciplina" %>
	</p>
<% end %>

<%= link_to "Voltar",  courses_path %>

app/views/courses/show.html.erb
<h1><%= @course.name %></h1>

app/views/home/index.html.erb
<ul class="breadcrumb breadcrumb-page">
	<div class="breadcrumb-label text-light-gray">Você está em: </div>
	<li><a href="#">Início</a></li>
</ul>


<div class="page-header">
	<div class="row">
		<h1 class="col-xs-12 col-sm-4 text-center text-left-sm">
			<i class="fa fa-dashboard page-header-icon"></i>&nbsp;&nbsp;Início</h1>
	</div>
</div>

<div class="row">
	<div class="col-lg-9 col-sm-8 col-xs-12">
		<div class="stat-panel">
			<div class="stat-cell bg-success valign-middle">
				<i class="fa fa-group bg-icon"></i>
				<span class="text-xlg"><strong>10</strong></span><br>
				<span class="text-bg">Alguma coisa</span><br>
			</div> 
		</div>
	</div>
	<div class="col-lg-3 col-sm-4 col-xs-12">
		<div style="height: 147px;" class="stat-panel">
			<div class="stat-row">
				<div class="stat-cell bg-danger no-padding text-center text-slg">
					<i class="fa fa-envelope"></i>
				</div>
			</div>
			<div class="stat-row">
				<div class="stat-cell bordered no-border-t text-center text-lg">
					<strong>10</strong>
					<small><small>Contatos</small></small>
				</div>
			</div> 
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<title>Painel CACC</title>

	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">

	
    <%= javascript_include_tag 'application' %>
	<%= stylesheet_link_tag    'application', 'http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,600,700,300&subset=latin' %>

</head>
<body class="theme-default main-menu-animated">

	<script>var init = [];</script>

	<div id="main-wrapper">

		<!-- Barra do topo -->
		<div id="main-navbar" class="navbar navbar-inverse" role="navigation">
			<button type="button" id="main-menu-toggle"><i class="navbar-icon fa fa-bars icon"></i>
				<span class="hide-menu-text">ESCONDER MENU</span></button>
			<div class="navbar-inner">
				<div class="navbar-header">

					<a href="" class="navbar-brand">
						<div>
						<img alt="Pixel Admin" src="images/pixel-admin/main-navbar-logo.png"></div>
						PAINEL<strong>CACC</strong>
					</a>

					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-navbar-collapse"><i class="navbar-icon fa fa-bars"></i></button>

				</div>

				<div id="main-navbar-collapse" class="collapse navbar-collapse main-navbar-collapse">
					<div>

						<!-- Menu esquerdo do topo -->
						<ul class="nav navbar-nav">
							<li>
								<a href="/">Início</a>
							</li>
						</ul>

						<!-- Menu direito do topo -->
						<div class="right clearfix">
							<ul class="nav navbar-nav pull-right right-navbar-nav">
								<li class="dropdown">
									<a href="\#" class="dropdown-toggle user-menu" data-toggle="dropdown">
										<img src="images/pixel-admin/avatar.png" alt="" class="">
										<span>Rafael Rubenich</span>
									</a>
									<ul class="dropdown-menu">
										<li><a href="#"><i class="dropdown-icon fa fa-cog"></i>&nbsp;&nbsp;Settings</a></li>
										<li class="divider"></li>
										<li><a href="#"><i class="dropdown-icon fa fa-power-off"></i>&nbsp;&nbsp;Log Out</a></li>
									</ul>
								</li>
							</ul> 
						</div>
					</div>
				</div>
			</div> 
		</div> 

		<!-- Fim da barra do topo -->

		<!-- Menu de navegação lateral -->
		
		<div id="main-menu" role="navigation">			
			<div id="main-menu-inner">
				<div class="menu-content top" id="menu-content-demo">
					<div>
						<div class="text-bg">
							<span class="text-slim">Bem vindo,</span> 
							<span class="text-semibold">NAME</span>
						</div>
						<img src="images/pixel-admin/avatar.png" alt="" class="">
						<div class="btn-group">
							<a href="#" class="btn btn-xs btn-primary btn-outline dark" style="padding:5px;">
							<i class="fa fa-cog"></i></a>
							<a href="#" class="btn btn-xs btn-danger btn-outline dark" style="padding:5px;">
							<i class="fa fa-power-off"></i></a>
						</div>
					</div>
				</div>
				<ul class="navigation">
					<li>
						<a href="/">
							<i class="menu-icon fa fa-home"></i>
							<span class="mm-text">Início</span>
						</a>
					</li>
					<li class="mm-dropdown">
						<a href="#">
							<i class="menu-icon fa fa-folder"></i>
							<span class="mm-text">Banco de Provas</span>
						</a>
						<ul>
							<li>
								<a tabindex="-1" href="/tests">
									<i class="menu-icon fa fa-th-list"></i>
									<span class="mm-text">Listar</span>
								</a>
							</li>
							<li>
								<a tabindex="-1" href="/tests/new">
									<i class="menu-icon fa fa-plus"></i>
									<span class="mm-text">Adicionar</span>
								</a>
							</li>
						</ul>
					</li>

					<li class="mm-dropdown">
						<a href="#">
							<i class="menu-icon fa fa-group"></i>
							<span class="mm-text">Professores</span>
						</a>
						<ul>
							<li>
								<a tabindex="-1" href="/teachers">
									<i class="menu-icon fa fa-th-list"></i>
									<span class="mm-text">Listar</span>
								</a>
							</li>
							<li>
								<a tabindex="-1" href="/teachers/new">
									<i class="menu-icon fa fa-plus"></i>
									<span class="mm-text">Adicionar</span>
								</a>
							</li>
						</ul>
					</li>

					<li class="mm-dropdown">
						<a href="#">
							<i class="menu-icon fa fa-book"></i>
							<span class="mm-text">Disciplinas do Curso</span>
						</a>
						<ul>
							<li>
								<a tabindex="-1" href="/courses">
									<i class="menu-icon fa fa-th-list"></i>
									<span class="mm-text">Listar</span>
								</a>
							</li>
							<li>
								<a tabindex="-1" href="/courses/new">
									<i class="menu-icon fa fa-plus"></i>
									<span class="mm-text">Adicionar</span>
								</a>
							</li>
						</ul>
					</li>
					<li class="mm-dropdown">
						<a href="#">
							<i class="menu-icon fa fa-user"></i>
							<span class="mm-text">Alunos do Curso</span>
						</a>
						<ul>
							<li>
								<a tabindex="-1" href="/users">
									<i class="menu-icon fa fa-th-list"></i>
									<span class="mm-text">Listar</span>
								</a>
							</li>
							<li>
								<a tabindex="-1" href="/users/new">
									<i class="menu-icon fa fa-plus"></i>
									<span class="mm-text">Adicionar</span>
								</a>
							</li>
						</ul>
					</li>
				</ul>
			</div>
		</div> 

		<!-- Fim do menu de navegação -->

		<!-- Conteúdo da página -->

		<div id="content-wrapper">
			<%= yield %>
		</div>

		<!-- Fim do conteúdo da página -->


		<div id="main-menu-bg"></div>
	</div>
	<script type="text/javascript">
		window.PixelAdmin.start(init);
		console.log("Chamou")
	</script>

</body>
</html>

app/views/teachers/edit.html.erb
<h1>Editar Cliente</h1>
<br />
<%= form_for @teacher, url: {action: :update}  do |f| %>
	<% if @teacher.errors.any? %>
		<h2> Tem erro! </h2>
		<ul>
		<% @teacher.errors.full_messages.each do |message| %>
			<li> <%= message %> </li>
		<% end %>
		</ul>
	<% end %>

	<p>
		<%= f.label :name %> <br />
		<%= f.text_field :name %>
	</p>

	<p>
		<%= f.label :email %><br />
		<%= f.text_field :email %>
	</p>

	<p>
		<%= f.submit "Salvar Cliente" %>
	</p>
<% end %>

<%= link_to 'Voltar', teachers_path %>

app/views/teachers/index.html.erb
<ul class="breadcrumb breadcrumb-page">
	<div class="breadcrumb-label text-light-gray">Você está em: </div>
	<li><a href="#">Banco de Provas</a></li>
</ul>
<div class="page-header">
	<div class="row">
		<h1 class="col-xs-12 col-sm-4 text-center text-left-sm">
			<i class="fa fa-envelope page-header-icon"></i>&nbsp;&nbsp;Lista de Provas
		</h1>
	</div>
</div>
<div class="row">
	<div class="col-sm-12">
		<div class="panel">
			<div class="panel-heading">
				<span class="panel-title">Todas as provas</span>
			</div>
			<div class="panel-body">
				<table class="table">
					<thead>
						<tr>
							<th>Professor</th>
							<th>Email</th>
							<th>Opções</th>
						</tr>
					</thead>
					<tbody>
						<% @teachers.each do |t| %>
							<tr>
								<td><%= t.name %></td>
								<td><%= t.email %></td>
								<td>
									<%= link_to raw("<i class='fa fa-eye'></i>"), teacher_path(t) %> 
									<%= link_to raw("<i class='fa fa-edit'></i>"), edit_teacher_path(t) %> 
									<%= link_to raw("<i class='fa fa-trash-o'></i>"), teacher_path(t), 
											method: :delete, data: {confirm: 'Deletar?'}%>
								</td>
							</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

app/views/teachers/new.html.erb
<h1>Novo Cliente</h1>
<br />

<%= form_for @teacher do |f| %>
	<% if @teacher.errors.any? %>
		<h2> Tem erro! </h2>
		<ul>
		<% @teacher.errors.full_messages.each do |message| %>
			<li> <%= message %> </li>
		<% end %>
		</ul>
	<% end %>

	<p>
		<%= f.label :name %> <br />
		<%= f.text_field :name %>
	</p>

	<p>
		<%= f.label :email %><br />
		<%= f.email_field :email %>
	</p>
	<p>
		<%= f.submit "Novo Usuario" %>
	</p>
<% end %>

<%= link_to "Voltar",  users_path %>

app/views/teachers/show.html.erb
<h1><%= @teacher.name %></h1>

<p><%= @teacher.email %></p>

<h2>Add a course:</h2>
<%= form_for([@teacher, @teacher.teacher_course.build]) do |f| %>
  <p>
 	<%= f.collection_select :course_id, Course.order(:name),:id,:name, :prompt => "Disciplina"%>
  </p>
  <p>
	<%= f.collection_select :course_type_id, CourseType.order(:name),:id,:name, :prompt => "Tipo" %>
  </p>
  <p>
	  <%= f.label :year %>
	  <%= f.number_field :year %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/users/edit.html.erb
<h1>Editar Cliente</h1>
<br />
<%= form_for @client, url: {action: :update}  do |f| %>
	<% if @client.errors.any? %>
		<h2> Tem erro! </h2>
		<ul>
		<% @client.errors.full_messages.each do |message| %>
			<li> <%= message %> </li>
		<% end %>
		</ul>
	<% end %>

	<p>
		<%= f.label :name %> <br />
		<%= f.text_field :name %>
	</p>

	<p>
		<%= f.label :website %><br />
		<%= f.text_field :website %>
	</p>

	<p>
		<%= f.label :description %><br />
		<%= f.text_area :description %>
	</p>
	
	<p>
		<%= f.submit "Salvar Cliente" %>
	</p>
<% end %>

<%= link_to 'Voltar', client_path %>

app/views/users/index.html.erb
<h2> Usuarios </h2>
<% @users.each do |u| %>
	<%= u.name %>
	<br />
<% end %>

app/views/users/new.html.erb
<h1>Novo Usuario</h1>
<br />

<%= form_for(@user, html: {multipart: true} ) do |f| %>
	<% if @user.errors.any? %>
		<h2> Tem erro! </h2>
		<ul>
		<% @user.errors.full_messages.each do |message| %>
			<li> <%= message %> </li>
		<% end %>
		</ul>
	<% end %>

	<p>
		<%= f.label :name %> <br />
		<%= f.text_field :name %>
	</p>

	<p>
		<%= f.label :nick %><br />
		<%= f.text_field :nick %>
	</p>

	<p>
		<%= f.label :email %><br />
		<%= f.text_field :email %>
	</p>

	<p>
		<%= f.label :avatar %><br />
		<%= f.file_field :avatar %>
	</p>
	
	<p>
		<%= f.submit "Novo Usuario" %>
	</p>
<% end %>

<%= link_to "Voltar",  users_path %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<p><%= @user.nick %></p>
<p><%= image_tag @user.avatar.url(:thumb) %> </p>